---
name: Build & Publish Latest Image

on:
  push:
    branches:
      - "master"

jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: |
            src:
              - '.github/workflows/ci.yaml'
              - 'Dockerfile'
              - 'src/**'

  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    needs: changes
    if: |
      (needs.changes.outputs.src == 'true')

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Set environment variables
      - run: echo RELEASE=$(cat ./src/package.json | jq -r .release) >> $GITHUB_ENV

      # Build & Publish
      - name: Build & Publish Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
          tags: joshuakraitberg/wg-easy:latest
